### ISSUE TITLE
2.5.0 release

### ISSUE THREAD

**Issue by iGranDav** [at-internet/atinternet-ios-swift-sdk#16]
Hi, 

Could you please help me locating the 2.5.0 release? https://developers.atinternet-solutions.com/apple-fr/changelog-apple-swift-fr/#2-5-0

What is this new SDK? https://github.com/at-internet/atinternet-apple-sdk and why versions numbers does not corresponds to actual releases (aka. SmartSDK mentionned in 2.5.0 changelog and this new SDK Readme)

Thanks

**Comment by d-theo** [comment]
Hi, 

Our 2.5.x SDK has been released with the auto tracking feature and is available at our [SDK download page](https://apps.atinternet-solutions.com/TagComposer/#/apple) or at https://github.com/at-internet/atinternet-apple-sdk

Furthermore we made the library universal (tvOS, watchOS, iOS, Swift, ObjC) so the architecture of the project is heavily changed and we decided to make a new github repository and also decided to reset cocoapods versioning - which I admit is confusing because we had trouble on how to manage the versioning of the swift2.3-compat branch.

regards

**Comment by iGranDav** [comment]
Closing, since info was solved by phone at that time.
